// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package language

import (
	"fmt"
	"log/slog"
	"strings"
	"time"
	"unicode"

	"github.com/googleapis/google-cloud-rust/generator/internal/api"
	"github.com/iancoleman/strcase"
)

type GoTemplateData struct {
	TemplateDir   string
	Name          string
	Title         string
	Description   string
	PackageName   string
	HasServices   bool
	CopyrightYear string
	BoilerPlate   []string
	Imports       []string
	DefaultHost   string
	Services      []*RustService
	Messages      []*RustMessage
	NameToLower   string
}

func NewGoTemplateData(api *api.API, c *goCodec) *GoTemplateData {
	year, _, _ := time.Now().Date()

	return &GoTemplateData{
		TemplateDir:   goTemplateDir(),
		Name:          api.Name,
		Title:         api.Title,
		Description:   api.Description,
		PackageName:   goPackageName(c, api),
		HasServices:   len(api.Services) > 0,
		CopyrightYear: fmt.Sprintf("%04d", year),
		BoilerPlate: append(licenseHeaderBulk(),
			"",
			" Code generated by sidekick. DO NOT EDIT."),
		Imports: goImports(),
		DefaultHost: func() string {
			if len(api.Services) > 0 {
				return api.Services[0].DefaultHost
			}
			return ""
		}(),
		Services: mapSlice(api.Services, func(s *api.Service) *Service {
			return newService(s, c, state)
		}),
		Messages: mapSlice(api.Messages, func(m *api.Message) *Message {
			return newMessage(m, c, api.State)
		}),
		NameToLower: strings.ToLower(api.Name),
	}
}

func newGoCodec(a *api.API, options map[string]string) (*goCodec, error) {
	codec := &goCodec{
		ImportMap: map[string]*goImport{},
	}
	if err := goValidate(codec, a); err != nil {
		return nil, err
	}
	for key, definition := range options {
		switch {
		case key == "package-name-override":
			codec.PackageNameOverride = definition
		case key == "go-package-name":
			codec.GoPackageName = definition
		case strings.HasPrefix(key, "import-mapping"):
			keys := strings.Split(key, ":")
			if len(keys) != 2 {
				return nil, fmt.Errorf("key should be in the format import-mapping:proto.path, got=%q", key)
			}
			defs := strings.Split(definition, ";")
			if len(defs) != 2 {
				return nil, fmt.Errorf("%s should be in the format path;name, got=%q", definition, keys[1])
			}
			codec.ImportMap[keys[1]] = &goImport{
				Path: defs[0],
				Name: defs[1],
			}
		}
	}
	goLoadWellKnownTypes(a.State)
	return codec, nil
}

type goCodec struct {
	// The source package name (e.g. google.iam.v1 in Protobuf). The codec can
	// generate code for one source package at a time.
	SourceSpecificationPackageName string
	// Package name override. If not empty, overrides the default package name.
	PackageNameOverride string
	// The package name to generate code into
	GoPackageName string
	// A map containing package id to import path information
	ImportMap map[string]*goImport
}

type goImport struct {
	Path string
	Name string
}

func goLoadWellKnownTypes(s *api.APIState) {
	timestamp := &api.Message{
		ID:      ".google.protobuf.Timestamp",
		Name:    "Time",
		Package: "time",
	}
	duration := &api.Message{
		ID:      ".google.protobuf.Duration",
		Name:    "Duration",
		Package: "time",
	}
	s.MessageByID[timestamp.ID] = timestamp
	s.MessageByID[duration.ID] = duration
}

func goFieldType(f *api.Field, state *api.APIState) string {
	var out string
	switch f.Typez {
	case api.STRING_TYPE:
		out = "string"
	case api.INT64_TYPE:
		out = "int64"
	case api.INT32_TYPE:
		out = "int32"
	case api.BOOL_TYPE:
		out = "bool"
	case api.BYTES_TYPE:
		out = "[]byte"
	case api.MESSAGE_TYPE:
		m, ok := state.MessageByID[f.TypezID]
		if !ok {
			slog.Error("unable to lookup type", "id", f.TypezID)
			return ""
		}
		if m.IsMap {
			key := goFieldType(m.Fields[0], state)
			val := goFieldType(m.Fields[1], state)
			out = "map[" + key + "]" + val
			break
		}
		out = "*" + goMessageName(m, state)
	case api.ENUM_TYPE:
		e, ok := state.EnumByID[f.TypezID]
		if !ok {
			slog.Error("unable to lookup type", "id", f.TypezID)
			return ""
		}
		out = goEnumName(e, state)
	default:
		slog.Error("unhandled fieldType", "type", f.Typez, "id", f.TypezID)
	}
	return out
}

func goAsQueryParameter(f *api.Field, state *api.APIState) string {
	return fmt.Sprintf("req.%s.to_str()", goToCamel(f.Name))
}

func goTemplateDir() string {
	return "go"
}

func goMethodInOutTypeName(id string, s *api.APIState) string {
	if id == "" {
		return ""
	}
	m, ok := s.MessageByID[id]
	if !ok {
		slog.Error("unable to lookup type", "id", id)
		return ""
	}
	return strcase.ToCamel(m.Name)
}

func goMessageName(m *api.Message, state *api.APIState) string {
	if m.Parent != nil {
		return goMessageName(m.Parent, state) + "_" + strcase.ToCamel(m.Name)
	}
	if imp, ok := goImportMap[m.Package]; ok {
		return imp.Name + "." + goToPascal(m.Name)
	}
	return goToPascal(m.Name)
}

func goFQMessageName(m *api.Message, state *api.APIState) string {
	return goMessageName(m, state)
}

func goEnumName(e *api.Enum, state *api.APIState) string {
	if e.Parent != nil {
		return goMessageName(e.Parent, state) + "_" + strcase.ToCamel(e.Name)
	}
	return strcase.ToCamel(e.Name)
}

func goFQEnumName(e *api.Enum, state *api.APIState) string {
	return goEnumName(e, state)
}

func goEnumValueName(e *api.EnumValue, state *api.APIState) string {
	if e.Parent.Parent != nil {
		return goMessageName(e.Parent.Parent, state) + "_" + strings.ToUpper(e.Name)
	}
	return strings.ToUpper(e.Name)
}

func goFQEnumValueName(v *api.EnumValue, state *api.APIState) string {
	return goEnumValueName(v, state)
}

func goOneOfType(o *api.OneOf, _ *api.APIState) string {
	panic("not needed for Go")
}

func goBodyAccessor(m *api.Method, state *api.APIState) string {
	if m.PathInfo.BodyFieldPath == "*" {
		// no accessor needed, use the whole request
		return ""
	}
	return "." + strcase.ToCamel(m.PathInfo.BodyFieldPath)
}

func goHTTPPathFmt(m *api.PathInfo, state *api.APIState) string {
	fmt := ""
	for _, segment := range m.PathTemplate {
		if segment.Literal != nil {
			fmt = fmt + "/" + *segment.Literal
		} else if segment.FieldPath != nil {
			fmt = fmt + "/%s"
		} else if segment.Verb != nil {
			fmt = fmt + ":" + *segment.Verb
		}
	}
	return fmt
}

func goHTTPPathArgs(h *api.PathInfo, state *api.APIState) []string {
	var args []string
	// TODO(codyoss): https://github.com/googleapis/google-cloud-rust/issues/34
	for _, segment := range h.PathTemplate {
		if segment.FieldPath != nil {
			// TODO(#34) - handle nested path params
			args = append(args, fmt.Sprintf(", req.%s", strcase.ToCamel(*segment.FieldPath)))
		}
	}
	return args
}

func goQueryParams(m *api.Method, state *api.APIState) []*api.Field {
	msg, ok := state.MessageByID[m.InputTypeID]
	if !ok {
		slog.Error("unable to lookup type", "id", m.InputTypeID)
		return nil
	}

	var queryParams []*api.Field
	for _, field := range msg.Fields {
		if !m.PathInfo.QueryParameters[field.JSONName] {
			continue
		}
		queryParams = append(queryParams, field)
	}
	return queryParams
}

func goToSnake(symbol string) string {
	return goEscapeKeyword(goToSnakeNoMangling(symbol))
}

func goToSnakeNoMangling(symbol string) string {
	if strings.ToLower(symbol) == symbol {
		return goEscapeKeyword(symbol)
	}
	return goEscapeKeyword(strcase.ToSnake(symbol))
}

func goToPascal(symbol string) string {
	return goEscapeKeyword(strcase.ToCamel(symbol))
}

func goToCamel(symbol string) string {
	return strcase.ToLowerCamel(symbol)
}

func goFormatDocComments(documentation string) []string {
	ss := strings.Split(documentation, "\n")
	for i := range ss {
		ss[i] = strings.TrimRightFunc(ss[i], unicode.IsSpace)
	}
	return ss
}

func goPackageName(c *goCodec, api *api.API) string {
	if len(c.PackageNameOverride) > 0 {
		return c.PackageNameOverride
	}
	return api.Name
}

func govalidatePackageName(c *goCodec, newPackage, elementName string) error {
	if c.SourceSpecificationPackageName == newPackage {
		return nil
	}
	// Special exceptions for mixin services
	if newPackage == "google.cloud.location" ||
		newPackage == "google.iam.v1" ||
		newPackage == "google.longrunning" {
		return nil
	}
	if c.SourceSpecificationPackageName == newPackage {
		return nil
	}
	return fmt.Errorf("rust codec requires all top-level elements to be in the same package want=%s, got=%s for %s",
		c.SourceSpecificationPackageName, newPackage, elementName)
}

func goValidate(c *goCodec, api *api.API) error {
	// Set the source package. We should always take the first service registered
	// as the source package. Services with mixes will register those after the
	// source package.
	if len(api.Services) > 0 {
		c.SourceSpecificationPackageName = api.Services[0].Package
	} else if len(api.Messages) > 0 {
		c.SourceSpecificationPackageName = api.Messages[0].Package
	}
	for _, s := range api.Services {
		if err := goValidatePackageName(c, s.Package, s.ID); err != nil {
			return err
		}
	}
	for _, s := range api.Messages {
		if err := goValidatePackageName(c, s.Package, s.ID); err != nil {
			return err
		}
	}
	for _, s := range api.Enums {
		if err := goValidatePackageName(s.Package, s.ID); err != nil {
			return err
		}
	}
	return nil
}

func goImports() []string {
	var imports []string
	for _, imp := range c.ImportMap {
		imports = append(imports, fmt.Sprintf("%q", imp.Path))
	}
	return imports
}

// The list of Golang keywords and reserved words can be found at:
//
// https://go.dev/ref/spec#Keywords
func goEscapeKeyword(symbol string) string {
	keywords := map[string]bool{
		"break":       true,
		"default":     true,
		"func":        true,
		"interface":   true,
		"select":      true,
		"case":        true,
		"defer":       true,
		"go":          true,
		"map":         true,
		"struct":      true,
		"chan":        true,
		"else":        true,
		"goto":        true,
		"package":     true,
		"switch":      true,
		"const":       true,
		"fallthrough": true,
		"if":          true,
		"range":       true,
		"type":        true,
		"continue":    true,
		"for":         true,
		"import":      true,
		"return":      true,
		"var":         true,
	}
	_, ok := keywords[symbol]
	if !ok {
		return symbol
	}
	return symbol + "_"
}
